namespace DomiNox.Dominex
{
    public enum DomiNexEffectType
    {
        AddCount,
        AddMult,
        AddCountPerDominoSumAtLeast,
        AddCountPerDominoSumAtMost,
        AddMultPerDominoSumAtLeast,
        AddMultPerDominoSumAtMost,
        AddMultPerDominoSumExactly,
        AddMultPerDouble,
        AddMultPerCreditStep,
        AddMultIfNoDiscard,
        AddCountIfPlacedAtLeast,
        AddCountToLastDomino,
        AddMultToFirstDomino,
        AddMultIfExactPlacedCount,
        AddMultIfFullNox,
        AddMultIfAnyDesignPattern,
        AddCountAndMultIfPattern,
        AddMultIfNoDiscardRemaining,
        AddMultPerCreditStepNoInterest,
        AddCountAndMultToFirstSumExactly,
        AddMultIfPattern,
        AddCountIfDominoSumAtMostCountAtLeast,
        AddCountPerDominoSumAtLeastWithPenalty,
        AddCountAndMultIfBossLevel,
        AddFirstDominoBaseCountAgain,
        AddFinalMultiplierIfValueAndDesignPattern,
        AddFinalMultiplierIfFullPlacedElseMultPenalty,
        AddMaxPlacedDominoes,
        AddCredits,
        FutureHook
    }
}
